### ISSUE TITLE
Feature request: be able to install a list dependencies on a new system

### ISSUE THREAD

**Issue by Lilja** [jsnjack/grm#1]
Thanks for GRM! I've thought about this problem for a while and how it's so stupid that we need to rely on package managers like `brew`/`apt` to manage CLI dependencies, when package maintainers literally uploads their binaries to the github releases. I was just about to begin type some stupid script when I tried once again to google "package manager github releases" and found this repo on the 6th item.

My problem is this:

I, probably like you @jsnjack manage dotfiles. Whenever I clone my dotfiles repo, I tend to want to install the CLI dependencies that I want. But you tend to forget what you install. Very much like how you "setup once and forget" which is a bad plague that tools like ansible, terraform is helping to irradicate.
These are a few dependencies I just installed:
* BurntSushi/ripgrep
* sharkdp/bat
* ogham/exa

How do I install these dependencies on a new system?

*Switching from my product-manager hat to my solution-hat*
Lots of different tools use `*-file` to manage configuration in files. Like `Dockerfile`, `Vagrantfile`, etc. What if there was a `Grmfile` that I could scribble down some fancy rust tools that I want version-controlled so whenever I git clone to a new system or pulling changes to my work machine, I could just `grm install -r Grmfile`(taking inspiration from pip here) and let grm handle the diffs and new additions? What say you?

**Comment by jsnjack** [comment]
Hi @Lilja! Glad to hear you like the tool :)

Interesting idea! I think the solution to your problem has already been implemented in a bit different way. 

grm already stores all data in `~/.config/grm/grm.yaml`, what you could try is just copying this file between systems and run `grm update`. It will parse `grm.yaml` file and make sure that all packages are installed

There is also a very simple "export" command to quickly install the same packages on a different machine. If you type `grm list -f` it will print the list of all installed packages (without versions though, so it might not be enough for you) which you could just quickly copy and paste to `grm install` command on a different machine

**Comment by Lilja** [comment]
Thanks @jsnjack, I will give that a try and evaluate the experience of doing that! Closing.
