### ISSUE TITLE
filter out "hidden" binaries

### ISSUE THREAD

**Issue by Lilja** [jsnjack/grm#12]
I just updated my FZF for my work-mac. With the 0.54.1 release the zip included a `._fzf` artefact from compiling in mac.

I opened an issue in fzf as it might not be intended to bundle this file in the build process. 

But it it might be good idea to filter out these files. As `grm` installed `._fzf`. 

```
lilja in ~/c/custom-data on touch-plugins λ grm install junegunn/fzf
Found release v0.54.1
Inspecting assets...
Found 1 suitable assets
  1) fzf-0.54.1-darwin_arm64.zip
Selected asset: fzf-0.54.1-darwin_arm64.zip
 100% |████████████████████████████████████████| (16.5 MB/s) [0s:0s]
Unpacking archive... fzf-0.54.1-darwin_arm64.zip
Looking for a binary file...
  ._fzf                                              application/octet-stream
  fzf                                                application/x-mach-binary
  fzf-0.54.1-darwin_arm64.zip                        application/zip
Installing ._fzf to /usr/local/bin/._fzf...
done
```

[fzf issue](https://github.com/junegunn/fzf/issues/3939)

**Comment by jsnjack** [comment]
oh interesting one, should be easy to prevent by filtering out everything that starts with `._`
