### ISSUE TITLE
Picking an asset should not be zero index based

### ISSUE THREAD

**Issue by Lilja** [jsnjack/grm#8]
This might be super opinionated and if you don't agree that's fine.

When i'm being prompted with an asset to pick, it should start with 1. 

Picking between 0 and 1 is kind of awkward as technically they are on the opposite sides of a qwerty keyboard.

**Comment by jsnjack** [comment]
> Picking between 0 and 1 is kind of awkward as technically they are on the opposite sides of a qwerty keyboard.

Good point! :D
